// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, openBlock as _openBlock } from 'vue'
// tslint:disable
/* eslint-disable */

export const gqlBlogGql = `query Blog(\$id: Int!) {
  blog(id: \$id) {
    result {
      id
      content
      posts(id: 3) {
        id
        content
      }
      meta
    }
  }
}
`
export const gqlBlogsGql = `query Blogs(\$pagination: Pagination!) {
  blogs(pagination: \$pagination) {
    result {
      id
      content
      posts(id: 1) {
        id
        content
      }
      meta
    }
  }
}
`
export const gqlCreateBlogGql = `mutation CreateBlog(\$content: String!) {
  createBlog(content: \$content) {
    result {
      id
      content
      posts(id: 2) {
        id
        content
      }
      meta
    }
  }
}
`
export function indexTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("div"))
}
/* eslint-enable */
// tslint:enable
