// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, createVNode as _createVNode, openBlock as _openBlock } from 'vue'
// tslint:disable
/* eslint-disable */

export const gqlBlogGql = `query Blog(\$id: Int!) {
  blog(id: \$id) {
    result {
      id
      content
      posts(id: 3) {
        id
        content
      }
      meta
    }
  }
}
`
export const gqlBlogsGql = `query Blogs(\$pagination: Pagination!) {
  blogs(pagination: \$pagination) {
    result {
      id
      content
      posts(id: 1) {
        id
        content
      }
      meta
    }
  }
}
`
export const gqlCreateBlogGql = `mutation CreateBlog(\$content: String!) {
  createBlog(content: \$content) {
    result {
      id
      content
      posts(id: 2) {
        id
        content
      }
      meta
    }
  }
}
`
export function indexTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("div", null, [
    _createVNode("input", {
      type: "file",
      onChange: _cache[1] || (_cache[1] = (...args) => (_ctx.onChange && _ctx.onChange(...args)))
    }, null, 32 /* HYDRATE_EVENTS */),
    _createVNode("button", {
      onClick: _cache[2] || (_cache[2] = (...args) => (_ctx.download && _ctx.download(...args)))
    }, "download"),
    _createVNode("button", {
      onClick: _cache[3] || (_cache[3] = (...args) => (_ctx.downloadData && _ctx.downloadData(...args)))
    }, "download data"),
    _createVNode("button", {
      onClick: _cache[4] || (_cache[4] = (...args) => (_ctx.getRawText && _ctx.getRawText(...args)))
    }, "get raw text")
  ]))
}
/* eslint-enable */
// tslint:enable
