type Blog {
  id: Float!
  content: String!
  posts: [Post]!
}

type Post {
  id: Float!
  content: String!
}

type Query {
  blogs: BlogsResult!
  blog(id: Float!): BlogResult!
}

type BlogsResult {
  result: [Blog]!
}

type BlogResult {
  result: Blog
}
