/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable

export const srcDataGql = `type Blog {
  id: Float!
  content: String!
  posts: [Post]!
}

type Post {
  id: Float!
  content: String!
}

type Query {
  blogs: BlogsResult!
  blog(id: Float!): BlogResult!
}

type BlogsResult {
  blogs: [Blog]!
}

type BlogResult {
  blog: Blog
}
`
// tslint:enable
